// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/role/get.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/role/get.go -destination=internal/usecases/role/mocks/get.go
//

// Package mock_role is a generated GoMock package.
package mock_role

import (
	context "context"
	reflect "reflect"

	role "github.com/tapiaw38/auth-api-be/internal/usecases/role"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUsecase is a mock of GetUsecase interface.
type MockGetUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUsecaseMockRecorder
	isgomock struct{}
}

// MockGetUsecaseMockRecorder is the mock recorder for MockGetUsecase.
type MockGetUsecaseMockRecorder struct {
	mock *MockGetUsecase
}

// NewMockGetUsecase creates a new mock instance.
func NewMockGetUsecase(ctrl *gomock.Controller) *MockGetUsecase {
	mock := &MockGetUsecase{ctrl: ctrl}
	mock.recorder = &MockGetUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUsecase) EXPECT() *MockGetUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUsecase) Execute(arg0 context.Context, arg1 role.GetFilterOptions) (*role.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*role.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUsecase)(nil).Execute), arg0, arg1)
}
