// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/datasources/repositories/refresh_token/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapters/datasources/repositories/refresh_token/repository.go -destination=internal/adapters/datasources/repositories/refresh_token/mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/tapiaw38/auth-api-be/internal/domain"
	errors "github.com/tapiaw38/auth-api-be/internal/platform/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.RefreshToken) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// GetByHash mocks base method.
func (m *MockRepository) GetByHash(arg0 context.Context, arg1 string) (*domain.RefreshToken, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", arg0, arg1)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockRepositoryMockRecorder) GetByHash(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockRepository)(nil).GetByHash), arg0, arg1)
}

// Revoke mocks base method.
func (m *MockRepository) Revoke(arg0 context.Context, arg1 string) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", arg0, arg1)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRepositoryMockRecorder) Revoke(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRepository)(nil).Revoke), arg0, arg1)
}

// RevokeAllForUser mocks base method.
func (m *MockRepository) RevokeAllForUser(arg0 context.Context, arg1 string) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", arg0, arg1)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRepositoryMockRecorder) RevokeAllForUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRepository)(nil).RevokeAllForUser), arg0, arg1)
}
