// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/change_password.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
)

// MockChangePasswordUsecase is a mock of ChangePasswordUsecase interface.
type MockChangePasswordUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChangePasswordUsecaseMockRecorder
}

// MockChangePasswordUsecaseMockRecorder is the mock recorder for MockChangePasswordUsecase.
type MockChangePasswordUsecaseMockRecorder struct {
	mock *MockChangePasswordUsecase
}

// NewMockChangePasswordUsecase creates a new mock instance.
func NewMockChangePasswordUsecase(ctrl *gomock.Controller) *MockChangePasswordUsecase {
	mock := &MockChangePasswordUsecase{ctrl: ctrl}
	mock.recorder = &MockChangePasswordUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangePasswordUsecase) EXPECT() *MockChangePasswordUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockChangePasswordUsecase) Execute(arg0 context.Context, arg1 user.ChangePasswordInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockChangePasswordUsecaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockChangePasswordUsecase)(nil).Execute), arg0, arg1)
}
