// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/change_password.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/user/change_password.go -destination=internal/usecases/user/mocks/change_password.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/auth-api-be/internal/platform/errors"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
	gomock "go.uber.org/mock/gomock"
)

// MockChangePasswordUsecase is a mock of ChangePasswordUsecase interface.
type MockChangePasswordUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChangePasswordUsecaseMockRecorder
	isgomock struct{}
}

// MockChangePasswordUsecaseMockRecorder is the mock recorder for MockChangePasswordUsecase.
type MockChangePasswordUsecaseMockRecorder struct {
	mock *MockChangePasswordUsecase
}

// NewMockChangePasswordUsecase creates a new mock instance.
func NewMockChangePasswordUsecase(ctrl *gomock.Controller) *MockChangePasswordUsecase {
	mock := &MockChangePasswordUsecase{ctrl: ctrl}
	mock.recorder = &MockChangePasswordUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangePasswordUsecase) EXPECT() *MockChangePasswordUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockChangePasswordUsecase) Execute(arg0 context.Context, arg1 user.ChangePasswordInput, arg2 string) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1, arg2)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockChangePasswordUsecaseMockRecorder) Execute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockChangePasswordUsecase)(nil).Execute), arg0, arg1, arg2)
}
