// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecases/user/getTokenVersion.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetTokenVersionUsecase is a mock of GetTokenVersionUsecase interface.
type MockGetTokenVersionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTokenVersionUsecaseMockRecorder
}

// MockGetTokenVersionUsecaseMockRecorder is the mock recorder for MockGetTokenVersionUsecase.
type MockGetTokenVersionUsecaseMockRecorder struct {
	mock *MockGetTokenVersionUsecase
}

// NewMockGetTokenVersionUsecase creates a new mock instance.
func NewMockGetTokenVersionUsecase(ctrl *gomock.Controller) *MockGetTokenVersionUsecase {
	mock := &MockGetTokenVersionUsecase{ctrl: ctrl}
	mock.recorder = &MockGetTokenVersionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTokenVersionUsecase) EXPECT() *MockGetTokenVersionUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetTokenVersionUsecase) Execute(arg0 context.Context, arg1 string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetTokenVersionUsecaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetTokenVersionUsecase)(nil).Execute), arg0, arg1)
}
