// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/login.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/user/login.go -destination=internal/usecases/user/mocks/login.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/auth-api-be/internal/platform/errors"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginUsecase is a mock of LoginUsecase interface.
type MockLoginUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUsecaseMockRecorder
	isgomock struct{}
}

// MockLoginUsecaseMockRecorder is the mock recorder for MockLoginUsecase.
type MockLoginUsecaseMockRecorder struct {
	mock *MockLoginUsecase
}

// NewMockLoginUsecase creates a new mock instance.
func NewMockLoginUsecase(ctrl *gomock.Controller) *MockLoginUsecase {
	mock := &MockLoginUsecase{ctrl: ctrl}
	mock.recorder = &MockLoginUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUsecase) EXPECT() *MockLoginUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginUsecase) Execute(arg0 context.Context, arg1 user.LoginInput) (*user.LoginOutput, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*user.LoginOutput)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginUsecase)(nil).Execute), arg0, arg1)
}
