// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/register.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
)

// MockRegisterUsecase is a mock of RegisterUsecase interface.
type MockRegisterUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterUsecaseMockRecorder
}

// MockRegisterUsecaseMockRecorder is the mock recorder for MockRegisterUsecase.
type MockRegisterUsecaseMockRecorder struct {
	mock *MockRegisterUsecase
}

// NewMockRegisterUsecase creates a new mock instance.
func NewMockRegisterUsecase(ctrl *gomock.Controller) *MockRegisterUsecase {
	mock := &MockRegisterUsecase{ctrl: ctrl}
	mock.recorder = &MockRegisterUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterUsecase) EXPECT() *MockRegisterUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterUsecase) Execute(arg0 context.Context, arg1 user.RegisterInput) (*user.RegisterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*user.RegisterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterUsecaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterUsecase)(nil).Execute), arg0, arg1)
}
