// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecases/user/request_reset_password.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	errors "github.com/tapiaw38/auth-api-be/internal/platform/errors"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
)

// MockRequestResetPasswordUsecase is a mock of RequestResetPasswordUsecase interface.
type MockRequestResetPasswordUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRequestResetPasswordUsecaseMockRecorder
}

// MockRequestResetPasswordUsecaseMockRecorder is the mock recorder for MockRequestResetPasswordUsecase.
type MockRequestResetPasswordUsecaseMockRecorder struct {
	mock *MockRequestResetPasswordUsecase
}

// NewMockRequestResetPasswordUsecase creates a new mock instance.
func NewMockRequestResetPasswordUsecase(ctrl *gomock.Controller) *MockRequestResetPasswordUsecase {
	mock := &MockRequestResetPasswordUsecase{ctrl: ctrl}
	mock.recorder = &MockRequestResetPasswordUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestResetPasswordUsecase) EXPECT() *MockRequestResetPasswordUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRequestResetPasswordUsecase) Execute(arg0 context.Context, arg1 string) (*user.RequestResetPasswordOutput, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*user.RequestResetPasswordOutput)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRequestResetPasswordUsecaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRequestResetPasswordUsecase)(nil).Execute), arg0, arg1)
}
