// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/reset_password.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/user/reset_password.go -destination=internal/usecases/user/mocks/reset_password.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/auth-api-be/internal/platform/errors"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
	gomock "go.uber.org/mock/gomock"
)

// MockResetPasswordUsecase is a mock of ResetPasswordUsecase interface.
type MockResetPasswordUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockResetPasswordUsecaseMockRecorder
	isgomock struct{}
}

// MockResetPasswordUsecaseMockRecorder is the mock recorder for MockResetPasswordUsecase.
type MockResetPasswordUsecaseMockRecorder struct {
	mock *MockResetPasswordUsecase
}

// NewMockResetPasswordUsecase creates a new mock instance.
func NewMockResetPasswordUsecase(ctrl *gomock.Controller) *MockResetPasswordUsecase {
	mock := &MockResetPasswordUsecase{ctrl: ctrl}
	mock.recorder = &MockResetPasswordUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetPasswordUsecase) EXPECT() *MockResetPasswordUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockResetPasswordUsecase) Execute(arg0 context.Context, arg1 user.ResetPasswordInput) (*user.ResetPasswordOutput, errors.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*user.ResetPasswordOutput)
	ret1, _ := ret[1].(errors.ApplicationError)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockResetPasswordUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockResetPasswordUsecase)(nil).Execute), arg0, arg1)
}
