// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecases/user/reset_password.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
)

// MockResetPasswordUsecase is a mock of ResetPasswordUsecase interface.
type MockResetPasswordUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockResetPasswordUsecaseMockRecorder
}

// MockResetPasswordUsecaseMockRecorder is the mock recorder for MockResetPasswordUsecase.
type MockResetPasswordUsecaseMockRecorder struct {
	mock *MockResetPasswordUsecase
}

// NewMockResetPasswordUsecase creates a new mock instance.
func NewMockResetPasswordUsecase(ctrl *gomock.Controller) *MockResetPasswordUsecase {
	mock := &MockResetPasswordUsecase{ctrl: ctrl}
	mock.recorder = &MockResetPasswordUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetPasswordUsecase) EXPECT() *MockResetPasswordUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockResetPasswordUsecase) Execute(arg0 context.Context, arg1 user.ResetPasswordInput) (*user.ResetPasswordOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*user.ResetPasswordOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockResetPasswordUsecaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockResetPasswordUsecase)(nil).Execute), arg0, arg1)
}
