// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/set_password.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/user/set_password.go -destination=internal/usecases/user/mocks/set_password.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/tapiaw38/auth-api-be/internal/platform/errors"
	user "github.com/tapiaw38/auth-api-be/internal/usecases/user"
	gomock "go.uber.org/mock/gomock"
)

// MockSetPasswordUsecase is a mock of SetPasswordUsecase interface.
type MockSetPasswordUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSetPasswordUsecaseMockRecorder
	isgomock struct{}
}

// MockSetPasswordUsecaseMockRecorder is the mock recorder for MockSetPasswordUsecase.
type MockSetPasswordUsecaseMockRecorder struct {
	mock *MockSetPasswordUsecase
}

// NewMockSetPasswordUsecase creates a new mock instance.
func NewMockSetPasswordUsecase(ctrl *gomock.Controller) *MockSetPasswordUsecase {
	mock := &MockSetPasswordUsecase{ctrl: ctrl}
	mock.recorder = &MockSetPasswordUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetPasswordUsecase) EXPECT() *MockSetPasswordUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSetPasswordUsecase) Execute(arg0 context.Context, arg1 user.SetPasswordInput) errors.ApplicationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(errors.ApplicationError)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSetPasswordUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSetPasswordUsecase)(nil).Execute), arg0, arg1)
}
