// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecases/user/verify_email.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerifyEmailUsecase is a mock of VerifyEmailUsecase interface.
type MockVerifyEmailUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyEmailUsecaseMockRecorder
}

// MockVerifyEmailUsecaseMockRecorder is the mock recorder for MockVerifyEmailUsecase.
type MockVerifyEmailUsecaseMockRecorder struct {
	mock *MockVerifyEmailUsecase
}

// NewMockVerifyEmailUsecase creates a new mock instance.
func NewMockVerifyEmailUsecase(ctrl *gomock.Controller) *MockVerifyEmailUsecase {
	mock := &MockVerifyEmailUsecase{ctrl: ctrl}
	mock.recorder = &MockVerifyEmailUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyEmailUsecase) EXPECT() *MockVerifyEmailUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockVerifyEmailUsecase) Execute(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockVerifyEmailUsecaseMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockVerifyEmailUsecase)(nil).Execute), arg0, arg1)
}
